ALTER TABLE "vendors" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vendor_team_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "jobs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "vendor_offers" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_photos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "job_checklists" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "work_certificates" ENABLE ROW LEVEL SECURITY;
